---

- name: "Install ssmtp"
  action: "{{ ansible_pkg_mgr }} pkg=ssmtp state=present"

- name: "ssmtp configuration"
  template: src=ssmtp.conf.j2 
            dest=/etc/ssmtp/ssmtp.conf
            owner=root
            group=mail
            mode=0644
